set(CMAKE_CXX_FLAGS_DEVELOPMENT "${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
set(CMAKE_C_FLAGS_DEVELOPMENT "${CMAKE_C_FLAGS_RELWITHDEBINFO}")
set(CMAKE_EXE_LINKER_FLAGS_DEVELOPMENT "${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}")
set(CMAKE_SHARED_LINKER_FLAGS_DEVELOPMENT "${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO}")

set(CMAKE_MAP_IMPORTED_CONFIG_DEVELOPMENT Release RelWithDebInfo "")

if(CMAKE_BUILD_TYPE STREQUAL "Development" OR "Development" IN_LIST CMAKE_CONFIGURATION_TYPES)
    set(PORTAL_PROFILE ON)
endif()