"""
Copyright © 2025 Jonatan Nevo.
Distributed under the MIT license (see LICENSE file).
"""
import pathlib
import sys
import re

FILE_TEMPLATE = """// Generated by make_frozen_map.py do not change!
#pragma once
#include <frozen/unordered_map.h>
#include <frozen/string.h>

static constexpr frozen::unordered_map<uint64_t, std::string_view, {map_size}> G_FROZEN_ID_TO_STRING = {{
{map_entries}
}};

static constexpr frozen::unordered_map<frozen::string, uint64_t, {map_size}> G_FROZEN_STRING_TO_ID = {{
{reversed_map_entries}
}};
"""

def main():
    output_file = pathlib.Path(sys.argv[1])
    inc_files = [pathlib.Path(arg) for arg in sys.argv[2:]]
    map_size = 0

    map_entries = []
    reversed_map_entries = []

    pattern = re.compile(r'\{\s*(\d+)\s*,\s*(".*?")\s*\},?')
    for file in inc_files:
        data = file.read_text().splitlines()
        data = [line for line in data if line.strip()]
        map_size += len(data)
        map_entries.extend(data)

        for line in data:
            match = pattern.search(line)
            if match:
                hash_id = match.group(1)
                string_value = match.group(2)
                reversed_entry = f"{{ {string_value}, {hash_id} }},"
                reversed_map_entries.append(reversed_entry)

    output = FILE_TEMPLATE.format(
        map_size=map_size,
        map_entries="\n".join(map_entries),
        reversed_map_entries="\n".join(reversed_map_entries)
    )
    print(output_file)

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(output)

if __name__ == '__main__':
    main()
